version: '2'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - code-network
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:fpm
    volumes:
      - ./:/var/www
    networks:
      - code-network

networks:
  code-network:
    driver: bridge